name: 'UpdateCNIP'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  auto_update:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3

      - name: 'Delete old files'
        run: rm -rf *.txt

      - name: 'Download cidr merger'
        run: |
          wget https://github.com/zhanhb/cidr-merger/releases/download/$(curl -Ls "https://api.github.com/repos/zhanhb/cidr-merger/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')/cidr-merger-linux-amd64 -O cidr-merger
          chmod +x cidr-merger

      - name: 'Download CNIP'
        run: |
          wget https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china.txt -O china-operator-ip.txt
          wget https://ispip.clang.cn/all_cn_cidr.txt -O ClangCNIP.txt
          wget https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt -O IPIPCNIP.txt

      - name: 'Merger CNIP'
        run: ./cidr-merger -o CNIP.txt china-operator-ip.txt ClangCNIP.txt IPIPCNIP.txt

      - name: 'Commit Files'
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "*.txt"
          git commit -m '定时更新'
          echo ::set-output name=status::success

      - name: 'GitHub Push'
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
